name: reflex-arc
version: 0.1.0.0
synopsis: A design system for Reflex Dom
description: See README at <https://github.com/ners/reflex-arc#readme>
maintainer: ners <ners@gmx.ch>
github: ners/reflex-arc
category: Graphics
license-file: LICENCE

language: GHC2021

default-extensions:
 - ApplicativeDo
 - DerivingStrategies
 - DeriveAnyClass
 - DerivingVia
 - DefaultSignatures
 - ExplicitNamespaces
 - OverloadedStrings
 - RecordWildCards
 - DeriveGeneric
 - DataKinds
 - TypeFamilies

ghc-options:
 - -Weverything
 - -Wno-safe
 - -Wno-unsafe
 - -Wno-missing-safe-haskell-mode
 - -Wno-implicit-prelude
 - -Wno-missing-kind-signatures
 - -Wno-missing-export-lists
 - -Wno-missing-import-lists
 - -Wno-missed-specialisations
 - -Wno-all-missed-specialisations
 - -Wno-orphans

when:
 - condition: os(darwin) || os(osx) || os(ios)
   frameworks: Foundation
   ghc-options: -dynamic

dependencies:
  - base
  - base64
  - bytestring
  - clay
  - containers
  - data-default
  - file-embed
  - reflex
  - reflex-dom
  - ghc-syntax-highlighter
  - skylighting
  - text
  - web-font-mdi

when:
  - condition: os(osx) || os(ios)
    ghc-options:
      - -dynamic

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - reflex-arc
  ghc-options:
    - -threaded
