name: reflex-arc
version: 0.1.0.0
synopsis: A design system for Reflex Dom
description: See README at <https://github.com/ners/reflex-arc#readme>
maintainer: ners <ners@gmx.ch>
github: ners/reflex-arc
category: Graphics
license-file: LICENCE

dependencies:
  - base
  - base64
  - bytestring
  - clay
  - containers
  - data-default
  - file-embed
  - reflex
  - reflex-dom
  - reflex-dom-mdi
  - text

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - reflex-arc
  ghc-options:
    - -dynamic
    - -threaded

default-extensions:
  - DefaultSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
