name: reflex-dom-mdi
version: 0.1.0.0
description: See README at <https://github.com/ners/reflex-arc#readme>
maintainer: ners <ners@gmx.ch>
github: ners/reflex-arc
category: Graphics

dependencies:
  - base
  - reflex-dom
  - text

library:
  source-dirs: src
  ld-options: -fuse-ld=gold
